<?php declare(strict_types=1);

namespace Fousky\Traits\Uuid;

use Doctrine\ORM\Mapping as ORM;
use Ramsey\Uuid\Uuid;

/**
 * @author Lukáš Brzák <lukas.brzak@fousky.cz>
 */
trait UuidAutogenerated
{
    /**
     * @var Uuid|null
     *
     * @ORM\Id()
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class="Ramsey\Uuid\Doctrine\UuidGenerator")
     * @ORM\Column(name="id", type="uuid")
     */
    protected $id;

    public function getId(): ?Uuid
    {
        return $this->id;
    }
}
